name: Continuous Deployment

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-server:
    name: Deploy Server
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy Server to Cloud Run
        run: |
          gcloud run deploy trackvenn-server \
            --source ./server \
            --region us-central1 \
            --project trackvenn \
            --allow-unauthenticated

  deploy-client:
    name: Deploy Client
    runs-on: ubuntu-latest
    # Wait for the server to finish deploying so we don't accidentally deploy if the server breaks
    needs: deploy-server
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Build React App
        working-directory: ./client
        run: |
          npm ci --legacy-peer-deps
          export REACT_APP_API_URL=$(gcloud run services describe trackvenn-server --region us-central1 --project trackvenn --format 'value(status.url)')/
          echo "Server URL: $REACT_APP_API_URL"
          CI=true REACT_APP_API_URL=$REACT_APP_API_URL npm run build

      - name: Deploy Client to Cloud Run
        run: |
          gcloud run deploy trackvenn-client \
            --source ./client \
            --region us-central1 \
            --project trackvenn \
            --allow-unauthenticated
